### ISSUE TITLE
plan to update to 1.6.8?

### ISSUE THREAD

**Issue by giuseppelt** [soulgame/cordova-plugin-tgsdk#1]
The official sdk is on 1.6.8. Is there a date for an updated version of this plugin?

Actually I use this, but I would like to use the updated network sdks that come builtin with the 1.6.8.
Thanks

**Comment by leenjewel** [comment]
Sorry wait for long time

Now we have upgraded TGSDK Cordova Plugin to 1.6.8

Please try it and have a good day :-)
